const cryptoTickers = { 
  AAVE: "Aave",
  ADA: "Cardano",
  ALGO: "Algorand",
  ATOM: "Cosmos",
  AVAX: "Avalanche",
  BCH: "Bitcoin Cash",
  BNB: "Binance Coin",
  BSV: "Bitcoin SV",
  BTC: "Bitcoin",
  BTCB: "Bitcoin BEP2",
  BTT: "BitTorrent",
  BUSD: "Binance USD",
  CAKE: "PancakeSwap",
  CEL: "Celsius",
  COMP: "Compound",
  CRO: "Crypto.com Coin",
  DAI: "Dai",
  DASH: "Dash",
  DCR: "Decred",
  DOGE: "Dogecoin",
  DOT: "Polkadot",
  EGLD: "Elrond",
  EOS: "EOS",
  ETC: "Ethereum Classic",
  ETH: "Ethereum",
  FIL: "Filecoin",
  FTT: "FTX Token",
  HBAR: "Hedera Hashgraph",
  HT: "Huobi Token",
  ICP: "Internet Computer",
  KLAY: "Klaytn",
  KSM: "Kusama",
  LEO: "UNUS SED LEO",
  LINK: "Chainlink",
  LTC: "Litecoin",
  LUNA: "Terra",
  MATIC: "Polygon",
  MIOTA: "IOTA",
  MKR: "Maker",
  NEO: "Neo",
  RUNE: "THORChain",
  SHIB: "SHIBA INU",
  SOL: "Solana",
  THETA: "THETA",
  TRX: "TRON",
  UNI: "Uniswap",
  USDC: "USD Coin",
  USDT: "Tether",
  UST: "TerraUSD",
  VET: "VeChain",
  WBTC: "Wrapped Bitcoin",
  XEM: "NEM",
  XLM: "Stellar",
  XMR: "Monero",
  XRP: "XRP",
  XTZ: "Tezos",
  YFI: "yearn.finance",
  ZEC: "Zcash"
}

const stockTickers = {
  appl: "apple",
  msft: "microsoft",
  amzn: "amazon",
  goog: "google",
  googl: "google",
  fb: "facebook",
  tsla: "tesla",
};



const assetClasses = [
  "crypto",
  "cryptocurrency",
  "stocks",
  "bonds",
  "index fund",
  "gold",
];

module.exports = Object.freeze({
  cryptoTickers: cryptoTickers,
  stockTickers: stockTickers,
  assetClasses: assetClasses
})
